version: "3.8"

services:
  user-service:
    build: ./services/user-service
    ports:
      - "8000:8000"
    env_file:
      - ./services/user-service/.env
    networks:
      - ecommerce-network

  product-service:
    build: ./services/product-service
    ports:
      - "8001:8001"
    env_file:
      - ./services/product-service/.env
    networks:
      - ecommerce-network

  order-service:
    build: ./services/order-service
    ports:
      - "8002:8002"
    env_file:
      - ./services/order-service/.env
    networks:
      - ecommerce-network

  inventory-service:
    build: ./services/inventory-service
    ports:
      - "8003:8003"
    env_file:
      - ./services/inventory-service/.env
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
