version: '3.8'

services:
  user-service:
    build: ./services/user-service
    ports:
      - "8000:8000"
    env_file:
      - ./services/user-service/.env
    networks:
      - ecommerce-network

  product-service:
    build: ./services/product-service
    ports:
      - "8001:8001"
    env_file:
      - ./services/product-service/.env
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
