version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network

  user-service:
    build: ./services/user-service
    ports:
      - "8000:8000"
    env_file:
      - ./services/user-service/.env
    networks:
      - ecommerce-network

  product-service:
    build: ./services/product-service
    ports:
      - "8001:8001"
    env_file:
      - ./services/product-service/.env
    networks:
      - ecommerce-network

  order-service:
    build: ./services/order-service
    ports:
      - "8002:8002"
    env_file:
      - ./services/order-service/.env
    depends_on:
      - inventory-service
    networks:
      - ecommerce-network

  inventory-service:
    build: ./services/inventory-service
    ports:
      - "8003:8003"
    env_file:
      - ./services/inventory-service/.env
    networks:
      - ecommerce-network

  notification-service:
    build: ./services/notification-service
    ports:
      - "8004:8004"
    env_file:
      - ./services/notification-service/.env
    depends_on:
      - rabbitmq
    networks:
      - ecommerce-network

  cart-service:
    build: ./services/cart-service
    ports:
      - "8005:8005"
    env_file:
      - ./services/cart-service/.env
    networks:
      - ecommerce-network
  payment-service:
    build: ./services/payment-service
    ports:
      - "8006:8006"
    env_file:
      - ./services/payment-service/.env
    networks:
      - ecommerce-network
  review-service:
    build: ./services/review-service
    ports:
      - "8007:8007"
    env_file:
      - ./services/review-service/.env
    networks:
      - ecommerce-network

  recommendation-service:
    build: ./services/recommendation-service
    ports:
      - "8008:8008"
    env_file:
      - ./services/recommendation-service/.env
    networks:
      - ecommerce-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network
networks:
  ecommerce-network:
    driver: bridge
